##############################################################################
# Copyright (c) 2014-20, Lawrence Livermore National Security, LLC and Conduit
# project contributors. See the COPYRIGHT file for details.
##############################################################################

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONDUIT_ALLOC_NAME: conduit_${CI_PIPELINE_ID}
  BUILD_ROOT: ${CI_BUILDS_DIR}/conduit_${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}
  INSTALL_ROOT: ${CI_BUILDS_DIR}/spack_uberenv
  SPACK_UPSTREAM: /usr/workspace/radiuss/spack-chain-parent/opt/spack

before_script:
  - date

after_script:
  - date

# There are no tests for now
stages:
  - allocate_resources
  - build
  - release_resources
  - clean

.srun_alloc: &srun_prefix |
  JOB_ID=$(squeue -h --name=${CONDUIT_ALLOC_NAME} --format=%A)
  [[ -n "${JOB_ID}" ]] && JOB_ID="--jobid=${JOB_ID}"
  RESOURCES="-N 1 -n 1 -c 12"
  export EXEC_PREFIX="srun ${JOB_ID} ${RESOURCES}"

# This is not a job, but contains project specific build commands
.build_toss_3_x86_64_ib_script:
  variables:
  script:
    - PREFIX="--prefix=${INSTALL_ROOT}_${SYS_TYPE}_${TOOLCHAIN}"
    - UPSTREAM="--upstream=${SPACK_UPSTREAM}"
    - SPEC="--spec=${PKG_SPEC}"
    - SCRIPT="scripts/uberenv/uberenv.py --install --run_tests ${SPEC} ${PREFIX} ${UPSTREAM}"
    - *srun_prefix
    - set -x; ${EXEC_PREFIX} ${SCRIPT}; set +x

# Butte uses a very different job allocation system
.build_blueos_3_ppc64le_ib_script:
  script:
    - PREFIX="--prefix=${INSTALL_ROOT}_${SYS_TYPE}_${TOOLCHAIN}"
    - UPSTREAM="--upstream=${SPACK_UPSTREAM}"
    - SPEC="--spec=${PKG_SPEC}"
    - SCRIPT="scripts/uberenv/uberenv.py --install --run_tests ${SPEC} ${PREFIX} ${UPSTREAM}"
    - set -x; lalloc 1 ${SCRIPT}; set +x

.build_blueos_3_ppc64le_ib_p9_script:
  extends: .build_blueos_3_ppc64le_ib_script

.clean_toss_3_x86_64_ib_script:
  script:
    - rm -rf ${INSTALL_ROOT}_{TOOLCHAIN}

# This is where jobs are included
include:
  - local: .gitlab/ci/build_quartz.yml
  - local: .gitlab/ci/build_lassen.yml


