##############################################################################
# Copyright (c) 2014-20, Lawrence Livermore National Security, LLC and Conduit
# project contributors. See the COPYRIGHT file for details.
##############################################################################

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONDUIT_ALLOC_NAME: conduit_${CI_PIPELINE_ID}
  BUILD_ROOT: ${CI_BUILDS_DIR}/conduit_${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}
  INSTALL_ROOT: ${CI_BUILDS_DIR}/spack_uberenv
  SPACK_UPSTREAM: /usr/workspace/radiuss/spack-chain-parent/opt/spack

before_script:
  - date

after_script:
  - date

# There are no tests for now
stages:
  - allocate_resources
  - build
  - update_and_build
  - release_resources
  - clean

.run_update_uberenv: &run_update_uberenv |
  [[ "${UPDATE_UBERENV}" == "ON" ]] && ./scripts/ci/update-uberenv.sh

.inc_update_uberenv:
  stage: update_and_build
  variables:
    UPDATE_UBERENV: "ON"
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "master"'

.def_uberenv_cmd: &def_uberenv_cmd |
  PREFIX="--prefix=${INSTALL_ROOT}_${SYS_TYPE}_${TOOLCHAIN}"
  UPSTREAM="--upstream=${SPACK_UPSTREAM}"
  SPEC="--spec=${PKG_SPEC}"
  UBERENV_CMD="scripts/uberenv/uberenv.py --install --run_tests ${SPEC} ${PREFIX} ${UPSTREAM}"


##################
# QUARTZ TEMPLATES
##################

# Share configuration of jobs for quartz
.quartz_common:
  tags:
    - shell
    - quartz
  timeout: 3h
  except:
    refs:
      - /_qnone/
    variables:
      - $CONDUIT_CI_QUARTZ == "OFF"

.def_srun_prefix: &def_srun_prefix |
  JOB_ID=$(squeue -h --name=${CONDUIT_ALLOC_NAME} --format=%A)
  [[ -n "${JOB_ID}" ]] && JOB_ID="--jobid=${JOB_ID}"
  RESOURCES="-N 1 -n 1 -c 12"
  export SRUN_PREFIX="srun ${JOB_ID} ${RESOURCES}"

# This is not a job, but contains project specific build commands
.build_toss_3_x86_64_ib_script:
  script:
    - *run_update_uberenv
    - *def_srun_prefix
    - *def_uberenv_cmd
    - set -x; ${SRUN_PREFIX} ${UBERENV_CMD}; set +x

####
# Generic qwartz job, extending build script
.build_quartz:
  extends: [.quartz_common, .build_toss_3_x86_64_ib_script]
  stage: build

.update_uberenv_and_build_quartz:
  extends: [.build_quartz, .inc_update_uberenv]

##################
# LASSEN TEMPLATES
##################

# Share configuration of jobs for butte and lassen
.build_blueos_3_ppc64le_ib_script:
  script:
    - *run_update_uberenv
    - *def_uberenv_cmd
    - set -x; lalloc 1 ${UBERENV_CMD}; set +x

.build_blueos_3_ppc64le_ib_p9_script:
  extends: .build_blueos_3_ppc64le_ib_script

.build_lassen:
  variables:
  tags:
    - shell
    - lassen
  stage: build
  extends: .build_blueos_3_ppc64le_ib_p9_script
  rules:
    - if: '$CI_COMMIT_BRANCH =~/_lnone/ || $CONDUIT_CI_LASSEN == "OFF"'
      when: never
    - when: on_success
  allow_failure: true

.update_uberenv_and_build_lassen:
  extends: [.build_lassen, .inc_update_uberenv]

################
# JOBS INCLUSION
################

# This is where jobs are included
include:
  - local: .gitlab/ci/build_quartz.yml
  - local: .gitlab/ci/build_lassen.yml
