##############################################################################
# Copyright (c) 2014-20, Lawrence Livermore National Security, LLC and Conduit
# project contributors. See the COPYRIGHT file for details.
##############################################################################

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONDUIT_ALLOC_NAME: conduit_${CI_PIPELINE_ID}
  BUILD_ROOT: ${CI_BUILDS_DIR}/conduit_${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}
  INSTALL_ROOT: ${CI_BUILDS_DIR}/spack_uberenv
  SPACK_UPSTREAM: /usr/workspace/radiuss/spack-chain-parent/opt/spack

before_script:
  - date

after_script:
  - date

# There are no tests for now
stages:
  - allocate_resources
  - build
  - release_resources
  - clean

.uberenv_cmd: &uberenv_cmd |
  PREFIX="--prefix=${INSTALL_ROOT}_${SYS_TYPE}_${TOOLCHAIN}"
  UPSTREAM="--upstream=${SPACK_UPSTREAM}"
  SPEC="--spec=${PKG_SPEC}"
  UBERENV_CMD="scripts/uberenv/uberenv.py --install --run_tests ${SPEC} ${PREFIX} ${UPSTREAM}"


##################
# QUARTZ TEMPLATES
##################

# Share configuration of jobs for quartz
.quartz_common:
  tags:
    - shell
    - quartz
  timeout: 3h
  except:
    refs:
      - /_qnone/
    variables:
      - $CONDUIT_CI_QUARTZ == "OFF"

.srun_alloc: &srun_prefix |
  JOB_ID=$(squeue -h --name=${CONDUIT_ALLOC_NAME} --format=%A)
  [[ -n "${JOB_ID}" ]] && JOB_ID="--jobid=${JOB_ID}"
  RESOURCES="-N 1 -n 1 -c 12"
  export SRUN_PREFIX="srun ${JOB_ID} ${RESOURCES}"

# This is not a job, but contains project specific build commands
.build_toss_3_x86_64_ib_script:
  variables:
  script:
    - *srun_prefix
    - *uberenv_cmd
    - set -x; ${SRUN_PREFIX} ${UBERENV_CMD}; set +x

####
# Generic qwartz job, extending build script
.build_quartz:
  extends:
    - .quartz_common
    - .build_toss_3_x86_64_ib_script
  stage: build


##################
# LASSEN TEMPLATES
##################

# Share configuration of jobs for butte and lassen
.build_blueos_3_ppc64le_ib_script:
  script:
    - *uberenv_cmd
    - set -x; lalloc 1 ${UBERENV_CMD}; set +x

.build_blueos_3_ppc64le_ib_p9_script:
  extends: .build_blueos_3_ppc64le_ib_script

.build_lassen:
  variables:
  tags:
    - shell
    - lassen
  stage: build
  extends: .build_blueos_3_ppc64le_ib_p9_script
  except:
    refs:
      - /_lnone/
    variables:
      - $CONDUIT_CI_LASSEN == "OFF"
  allow_failure: true


################
# JOBS INCLUSION
################

# This is where jobs are included
include:
  - local: .gitlab/ci/build_quartz.yml
  - local: .gitlab/ci/build_lassen.yml


