# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# Build documentation in the directory with Sphinx
sphinx:
   configuration: src/docs/sphinx/conf.py