###############################################################################
# Conduit CI Checks
###############################################################################
# Ref:
# https://aka.ms/yaml

# only build merge target pr to develop
trigger: none
pr:
  branches:
    include:
    - master

# fast fail sanity checks
stages:
- stage: Sanity
  jobs:
  - job: BLT_Time_Travel_Check
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: self
        clean: boolean
        submodules: recursive

      - script: |
          #######################################
          # run our sanity check script
          #######################################
          git fetch
          python scripts/ci/check_blt_time_travel.py
        displayName: 'BLT Time Travel Check'

# main checks
# TODO:
# - setup coverage
#
- stage: Main
  jobs:
  ###############################################################################
  # Ubuntu build and test, using spack to build tpls
  ###############################################################################
  - job: Ubuntu_16
    pool:
      vmImage: 'ubuntu-16.04'
    timeoutInMinutes: 0
    variables:
      COMPILER_CC: gcc-5
      COMPILER_CXX: g++-5
      COMPILER_FC: gfortran-5
    strategy:
      matrix:
        shared_minimal:
          BUILD_SHARED_LIBS: ON
          CMAKE_BUILD_TYPE: Debug
          ENABLE_COVERAGE: OFF
          ENABLE_MPI: OFF
          ENABLE_DOCS: OFF
          ENABLE_SILO: OFF
          ENABLE_ADIOS: OFF
          ENABLE_PYTHON: OFF
          CMAKE_VERSION: 3.9.4
          BLT_CXX_STD: c++11

        shared_py27:
          BUILD_SHARED_LIBS: ON
          CMAKE_BUILD_TYPE: Debug
          ENABLE_COVERAGE: ON
          ENABLE_MPI: ON
          ENABLE_DOCS: ON
          ENABLE_SILO: ON
          ENABLE_ADIOS: OFF
          ENABLE_PYTHON: ON
          PYTHON_VERSION: 2.7.14
          CMAKE_VERSION: 3.9.4
          BLT_CXX_STD: c++11

        shared_py36:
          BUILD_SHARED_LIBS: ON
          CMAKE_BUILD_TYPE: Debug
          ENABLE_COVERAGE: OFF
          ENABLE_MPI: ON
          ENABLE_DOCS: ON
          ENABLE_SILO: ON
          ENABLE_ADIOS: OFF
          ENABLE_PYTHON: ON
          PYTHON_VERSION: 3.6.3
          CMAKE_VERSION: 3.9.4
          BLT_CXX_STD: c++11

        shared_py37:
          BUILD_SHARED_LIBS: ON
          CMAKE_BUILD_TYPE: Debug
          ENABLE_COVERAGE: OFF
          ENABLE_MPI: ON
          ENABLE_DOCS: ON
          ENABLE_SILO: ON
          ENABLE_ADIOS: OFF
          ENABLE_PYTHON: ON
          PYTHON_VERSION: 3.7.6
          CMAKE_VERSION: 3.9.4
          BLT_CXX_STD: c++11

        static_py27:
          BUILD_SHARED_LIBS: OFF
          CMAKE_BUILD_TYPE: Debug
          ENABLE_COVERAGE: OFF
          ENABLE_MPI: ON
          ENABLE_DOCS: ON
          ENABLE_SILO: ON
          ENABLE_ADIOS: OFF
          ENABLE_PYTHON: ON
          PYTHON_VERSION: 2.7.14
          CMAKE_VERSION: 3.9.4
          BLT_CXX_STD: c++11
    steps:
      - checkout: self
        clean: boolean
        submodules: recursive

      - script: |
           ##################
           # setup build env
           ##################
           # output env
           cat etc/*rel*
           env
           # clean default paths
           sudo rm -rf /usr/local/lib/android/
           sudo rm -rf /usr/share/miniconda/
           # add extra repo and update
           sudo add-apt-repository ppa:ubuntu-toolchain-r/test
           sudo apt-get update
           # list pkgs we need
           export APT_PKGS=binutils
           export APT_PKGS="$APT_PKGS gcc-5"
           export APT_PKGS="$APT_PKGS g++-5"
           export APT_PKGS="$APT_PKGS gfortran-5"
           export APT_PKGS="$APT_PKGS openmpi-bin"
           export APT_PKGS="$APT_PKGS libopenmpi-dev"
           export APT_PKGS="$APT_PKGS libncurses-dev"
           export APT_PKGS="$APT_PKGS libssl-dev"
           export APT_PKGS="$APT_PKGS libblas-dev"
           export APT_PKGS="$APT_PKGS liblapack-dev"
           export APT_PKGS="$APT_PKGS zlib1g-dev"
           export APT_PKGS="$APT_PKGS libgdbm-dev"
           export APT_PKGS="$APT_PKGS libreadline-dev"
           export APT_PKGS="$APT_PKGS libsqlite3-dev"
           export APT_PKGS="$APT_PKGS libbz2-dev"
           # install pkgs we need
           sudo apt-get -y install $APT_PKGS
        displayName: 'Prepare build env'

      - script: |
           #################################
           # run uber to build tpls
           #################################
           #
           pwd
           # echo system python details
           which python
           python --version
           # setup spack spec
           export SPACK_SPEC="%gcc@5"
           # mpi
           if [ $ENABLE_MPI  = 'ON' ]; then export SPACK_SPEC="${SPACK_SPEC}+mpi"; fi
           if [ $ENABLE_MPI  = 'OFF' ]; then export SPACK_SPEC="${SPACK_SPEC}~mpi"; fi
           # silo
           if [ $ENABLE_SILO  = 'ON' ]; then export SPACK_SPEC="${SPACK_SPEC}+silo"; fi
           if [ $ENABLE_SILO  = 'OFF' ]; then export SPACK_SPEC="${SPACK_SPEC}~silo"; fi
           # adios
           if [ $ENABLE_ADIOS  = 'ON' ]; then export SPACK_SPEC="${SPACK_SPEC}+adios~zfp"; fi
           if [ $ENABLE_ADIOS  = 'OFF' ]; then export SPACK_SPEC="${SPACK_SPEC}~adios"; fi
           # python
           if [ $ENABLE_PYTHON  = 'ON' ]; then export SPACK_SPEC="${SPACK_SPEC}+python"; fi
           if [ $ENABLE_PYTHON  = 'OFF' ]; then export SPACK_SPEC="${SPACK_SPEC}~python"; fi
           # docs
           if [ $ENABLE_DOCS  = 'ON' ]; then export SPACK_SPEC="${SPACK_SPEC}+doc"; fi
           if [ $ENABLE_DOCS  = 'OFF' ]; then export SPACK_SPEC="${SPACK_SPEC}~doc"; fi
           # package ver selections and extra tweaks
           export SPACK_SPEC="${SPACK_SPEC} ^cmake@${CMAKE_VERSION}"
           export SPACK_SPEC="${SPACK_SPEC} ^python@${PYTHON_VERSION}"
           if [ $ENABLE_SILO = 'ON' ]; then export SPACK_SPEC="${SPACK_SPEC} ^silo~mpi"; fi
           # show final spec
           echo $SPACK_SPEC
           # run uber to build tpls
           python scripts/uberenv/uberenv.py -k --pull --spec "${SPACK_SPEC}" --spack-config-dir=scripts/uberenv/spack_configs/ci/ubuntu_16/
        displayName: 'Spack Build Tpls'

      - script: |
           #################################
           # configure
           #################################
           # setup compiler env vars
           export CC=${COMPILER_CC}
           export CXX=${COMPILER_CXX}
           export FC=${COMPILER_FC}
           ${CC} --version
           # capture current path
           export ROOT_DIR=`pwd`
           # find spack generated host config file
           export HOST_CONFIG=`ls ${ROOT_DIR}/uberenv_libs/*.cmake`
           echo $HOST_CONFIG
           # find spack installed cmake
           export CMAKE_BIN_DIR=`ls -d ${ROOT_DIR}/uberenv_libs/spack/opt/spack/*/*/cmake*/bin`
           export PATH=${CMAKE_BIN_DIR}:$PATH
           echo $PATH
           which cmake
           cmake --version
           # prepare build dir
           mkdir build
           cd build
           # setup cmake options
           export CMAKE_OPTS="-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
           export CMAKE_OPTS="${CMAKE_OPTS} -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}"
           export CMAKE_OPTS="${CMAKE_OPTS} -DENABLE_COVERAGE=${ENABLE_COVERAGE}"
           export CMAKE_OPTS="${CMAKE_OPTS} -DBLT_CXX_STD=${BLT_CXX_STD}"
           export CMAKE_OPTS="${CMAKE_OPTS} -DCMAKE_INSTALL_PREFIX=../install"
           # configure
           cmake ${CMAKE_OPTS} -C ${HOST_CONFIG} ../src
        displayName: 'Configure with CMake'

      - script: |
           #################################
           # build
           #################################
           # build
           cd build
           make VERBOSE=1
        displayName: 'Build'

      - script: |
           #################################
           # test
           #################################
           # find spack installed cmake
           export ROOT_DIR=`pwd`
           export CMAKE_BIN_DIR=`ls -d ${ROOT_DIR}/uberenv_libs/spack/opt/spack/*/*/cmake*/bin`
           export PATH=${CMAKE_BIN_DIR}:$PATH
           which ctest
           cd build
           # run ctest
           ctest -T test --output-on-failure -V
        displayName: 'Run Unit Tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'cTest'
          testResultsFiles: '**/Test.xml'
        displayName: 'Unit Test Results'
        condition: always()

      - task: CopyFiles@2
        inputs:
          contents: 'build/tests/_output/**'
          targetFolder: $(Build.ArtifactStagingDirectory)
        condition: always()

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: Conduit_Test_Outputs
        condition: always()

      - script: |
           #################################
           # install
           #################################
           cd build
           make install
        displayName: 'Install'

      - script: |
          ###########################
          # using with cmake example
          ###########################
          pwd
          ls -l
          # find spack installed cmake
          export ROOT_DIR=`pwd`
          export CMAKE_BIN_DIR=`ls -d ${ROOT_DIR}/uberenv_libs/spack/opt/spack/*/*/cmake*/bin`
          export PATH=${CMAKE_BIN_DIR}:$PATH
          echo $PATH
          which cmake
          cd install/examples/conduit/using-with-cmake
          mkdir _test_build
          cd _test_build
          cmake ../
          make VERBOSE=1
          ./conduit_example
        displayName: 'Test vs Install (using-with-cmake)'

      - script: |
          ###########################
          # using with make example
          ###########################
          cat install/share/conduit/conduit_config.mk
          pwd
          ls -l
          cd install/examples/conduit/using-with-make
          make
          ./conduit_example
        displayName: 'Test vs Install (using-with-make)'


  ###############################################################################
  # Ubuntu 18 build and test, using spack to build tpls
  #
  # When setup in Ascent, Azure didint have an Ubuntu 18 dev image, so we are 
  #  using the standard Ubuntu 18 container.
  #
  ###############################################################################
  - job: Ubuntu_18
    pool:
      vmImage: 'ubuntu-16.04'
    container: alpinedav/ascent-ci:ubuntu-18.04-dev
    timeoutInMinutes: 0
    variables:
      COMPILER_CC: gcc
      COMPILER_CXX: g++
      COMPILER_FC: gfortran
    strategy:
      matrix:
        shared_py36:
          BUILD_SHARED_LIBS: ON
          CMAKE_BUILD_TYPE: Debug
          ENABLE_COVERAGE: OFF
          ENABLE_MPI: ON
          ENABLE_DOCS: ON
          ENABLE_SILO: ON
          ENABLE_ADIOS: OFF
          ENABLE_PYTHON: ON
          PYTHON_VERSION: 3.6.3
          CMAKE_VERSION: 3.9.4
          BLT_CXX_STD: c++11
    steps:
      - checkout: self
        clean: boolean
        submodules: recursive

      - script: |
           ##################
           # setup build env
           ##################
           # output env
           cat etc/*rel*
           env
           sudo apt-get update
           # list pkgs we need
           export APT_PKGS=binutils
           export APT_PKGS="$APT_PKGS gcc"
           export APT_PKGS="$APT_PKGS g++"
           export APT_PKGS="$APT_PKGS gfortran"
           export APT_PKGS="$APT_PKGS python"
           export APT_PKGS="$APT_PKGS git"
           export APT_PKGS="$APT_PKGS curl"
           export APT_PKGS="$APT_PKGS unzip"
           export APT_PKGS="$APT_PKGS wget"
           export APT_PKGS="$APT_PKGS build-essential"
           export APT_PKGS="$APT_PKGS libncurses-dev"
           export APT_PKGS="$APT_PKGS libssl-dev"
           export APT_PKGS="$APT_PKGS libblas-dev"
           export APT_PKGS="$APT_PKGS liblapack-dev"
           export APT_PKGS="$APT_PKGS zlib1g-dev"
           export APT_PKGS="$APT_PKGS libgdbm-dev"
           export APT_PKGS="$APT_PKGS libreadline-dev"
           export APT_PKGS="$APT_PKGS libsqlite3-dev"
           export APT_PKGS="$APT_PKGS libbz2-dev"
           # install pkgs we need
           sudo apt-get -y install $APT_PKGS
        displayName: 'Prepare build env'

      - script: |
           #################################
           # run uber to build tpls
           #################################
           #
           pwd
           # echo system python details
           which python
           python --version
           # setup spack spec
           export SPACK_SPEC="%gcc@5"
           # mpi
           if [ $ENABLE_MPI  = 'ON' ]; then export SPACK_SPEC="${SPACK_SPEC}+mpi"; fi
           if [ $ENABLE_MPI  = 'OFF' ]; then export SPACK_SPEC="${SPACK_SPEC}~mpi"; fi
           # silo
           if [ $ENABLE_SILO  = 'ON' ]; then export SPACK_SPEC="${SPACK_SPEC}+silo"; fi
           if [ $ENABLE_SILO  = 'OFF' ]; then export SPACK_SPEC="${SPACK_SPEC}~silo"; fi
           # adios
           if [ $ENABLE_ADIOS  = 'ON' ]; then export SPACK_SPEC="${SPACK_SPEC}+adios~zfp"; fi
           if [ $ENABLE_ADIOS  = 'OFF' ]; then export SPACK_SPEC="${SPACK_SPEC}~adios"; fi
           # python
           if [ $ENABLE_PYTHON  = 'ON' ]; then export SPACK_SPEC="${SPACK_SPEC}+python"; fi
           if [ $ENABLE_PYTHON  = 'OFF' ]; then export SPACK_SPEC="${SPACK_SPEC}~python"; fi
           # docs
           if [ $ENABLE_DOCS  = 'ON' ]; then export SPACK_SPEC="${SPACK_SPEC}+doc"; fi
           if [ $ENABLE_DOCS  = 'OFF' ]; then export SPACK_SPEC="${SPACK_SPEC}~doc"; fi
           # package ver selections and extra tweaks
           export SPACK_SPEC="${SPACK_SPEC} ^cmake@${CMAKE_VERSION}"
           export SPACK_SPEC="${SPACK_SPEC} ^python@${PYTHON_VERSION}"
           if [ $ENABLE_SILO = 'ON' ]; then export SPACK_SPEC="${SPACK_SPEC} ^silo~mpi"; fi
           # show final spec
           echo $SPACK_SPEC
           # run uber to build tpls
           python scripts/uberenv/uberenv.py -k --pull --spec "${SPACK_SPEC}" --spack-config-dir=scripts/uberenv/spack_configs/ci/ubuntu_16/
        displayName: 'Spack Build Tpls'

      - script: |
           #################################
           # configure
           #################################
           # setup compiler env vars
           export CC=${COMPILER_CC}
           export CXX=${COMPILER_CXX}
           export FC=${COMPILER_FC}
           ${CC} --version
           # capture current path
           export ROOT_DIR=`pwd`
           # find spack generated host config file
           export HOST_CONFIG=`ls ${ROOT_DIR}/uberenv_libs/*.cmake`
           echo $HOST_CONFIG
           # find spack installed cmake
           export CMAKE_BIN_DIR=`ls -d ${ROOT_DIR}/uberenv_libs/spack/opt/spack/*/*/cmake*/bin`
           export PATH=${CMAKE_BIN_DIR}:$PATH
           echo $PATH
           which cmake
           cmake --version
           # prepare build dir
           mkdir build
           cd build
           # setup cmake options
           export CMAKE_OPTS="-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
           export CMAKE_OPTS="-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
           export CMAKE_OPTS="${CMAKE_OPTS} -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}"
           export CMAKE_OPTS="${CMAKE_OPTS} -DENABLE_COVERAGE=${ENABLE_COVERAGE}"
           export CMAKE_OPTS="${CMAKE_OPTS} -DBLT_CXX_STD=${BLT_CXX_STD}"
           export CMAKE_OPTS="${CMAKE_OPTS} -DCMAKE_INSTALL_PREFIX=../install"
           # configure
           cmake ${CMAKE_OPTS} -C ${HOST_CONFIG} ../src
        displayName: 'Configure with CMake'

      - script: |
           #################################
           # build
           #################################
           # build
           cd build
           make VERBOSE=1
        displayName: 'Build'

      - script: |
           #################################
           # test
           #################################
           # find spack installed cmake
           export ROOT_DIR=`pwd`
           export CMAKE_BIN_DIR=`ls -d ${ROOT_DIR}/uberenv_libs/spack/opt/spack/*/*/cmake*/bin`
           export PATH=${CMAKE_BIN_DIR}:$PATH
           which ctest
           cd build
           # run ctest
           ctest -T test --output-on-failure -V
        displayName: 'Run Unit Tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'cTest'
          testResultsFiles: '**/Test.xml'
        displayName: 'Unit Test Results'
        condition: always()

      - task: CopyFiles@2
        inputs:
          contents: 'build/tests/_output/**'
          targetFolder: $(Build.ArtifactStagingDirectory)
        condition: always()

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: Conduit_Test_Outputs
        condition: always()

      - script: |
           #################################
           # install
           #################################
           cd build
           make install
        displayName: 'Install'

      - script: |
          ###########################
          # using with cmake example
          ###########################
          pwd
          ls -l
          # find spack installed cmake
          export ROOT_DIR=`pwd`
          export CMAKE_BIN_DIR=`ls -d ${ROOT_DIR}/uberenv_libs/spack/opt/spack/*/*/cmake*/bin`
          export PATH=${CMAKE_BIN_DIR}:$PATH
          echo $PATH
          which cmake
          cd install/examples/conduit/using-with-cmake
          mkdir _test_build
          cd _test_build
          cmake ../
          make VERBOSE=1
          ./conduit_example
        displayName: 'Test vs Install (using-with-cmake)'

      - script: |
          ###########################
          # using with make example
          ###########################
          cat install/share/conduit/conduit_config.mk
          pwd
          ls -l
          cd install/examples/conduit/using-with-make
          make
          ./conduit_example
        displayName: 'Test vs Install (using-with-make)'

  ###############################################################################
  # Docker build and test case, that leverages our script that calls Docker Build
  ###############################################################################
  - job: Docker_Ubuntu
    pool:
      vmImage: 'ubuntu-16.04'
    timeoutInMinutes: 0
    steps:
      - checkout: self
        clean: boolean
        submodules: recursive

      - script: |
          ####################
          # run docker build
          ####################
          cd src/examples/docker/ubuntu/ && ./example_build.sh
        displayName: 'Docker Build'
