version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Submodule Init
          command: git submodule update --init --recursive
      - run:
          name: Docker Build
          command: cd src/examples/docker/ubuntu/ && ./example_build.sh
          no_output_timeout: 30m
