// Copyright (c) Lawrence Livermore National Security, LLC and other Conduit
// Project developers. See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to Conduit.

#ifndef CONDUIT_LICENSE_TEXT_HPP
#define CONDUIT_LICENSE_TEXT_HPP

std::string CONDUIT_LICENSE_TEXT = "Copyright (c) 2014-2020, Lawrence Livermore National Security, LLC.\n"
"\n"
"Produced at the Lawrence Livermore National Laboratory\n"
"\n"
"LLNL-CODE-666778\n"
"\n"
"All rights reserved.\n"
"\n"
"This file is part of Conduit.\n"
"\n"
"For details, see: http://software.llnl.gov/conduit/.\n"
"\n"
"Please also read conduit/LICENSE\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions are met:\n"
"\n"
"* Redistributions of source code must retain the above copyright notice,\n"
"this list of conditions and the disclaimer below.\n"
"\n"
"* Redistributions in binary form must reproduce the above copyright notice,\n"
"this list of conditions and the disclaimer (as noted below) in the\n"
"documentation and/or other materials provided with the distribution.\n"
"\n"
"* Neither the name of the LLNS/LLNL nor the names of its contributors may\n"
"be used to endorse or promote products derived from this software without\n"
"specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"\n"
"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n"
"ARE DISCLAIMED. IN NO EVENT SHALL LAWRENCE LIVERMORE NATIONAL SECURITY,\n"
"LLC, THE U.S. DEPARTMENT OF ENERGY OR CONTRIBUTORS BE LIABLE FOR ANY\n"
"DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
"DAMAGES  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS\n"
"OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n"
"HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\n"
"STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING\n"
"IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
"POSSIBILITY OF SUCH DAMAGE.\n"
"\n"
"Additional BSD Notice\n"
"\n"
"1. This notice is required to be provided under our contract with the U.S.\n"
"Department of Energy (DOE). This work was produced at Lawrence\n"
"Livermore National Laboratory under Contract No. DE-AC52-07NA27344 with\n"
"the DOE.\n"
"\n"
"2. Neither the United States Government nor Lawrence Livermore National\n"
"Security, LLC nor any of their employees, makes any warranty, express\n"
"or implied, or assumes any liability or responsibility for the\n"
"accuracy, completeness, or usefulness of any information, apparatus,\n"
"product, or process disclosed, or represents that its use would not\n"
"infringe privately-owned rights.\n"
"\n"
"3. Also, reference herein to any specific commercial products, process,\n"
"or services by trade name, trademark, manufacturer or otherwise does\n"
"not necessarily constitute or imply its endorsement, recommendation,\n"
"or favoring by the United States Government or Lawrence Livermore\n"
"National Security, LLC. The views and opinions of authors expressed\n"
"herein do not necessarily state or reflect those of the United\n"
"States Government or Lawrence Livermore National Security, LLC, and\n"
"shall not be used for advertising or product endorsement purposes.\n"
"\n"
"";

#endif

