name: build_conduit_windows

on:
  pull_request:
    branches: [ develop ]

jobs:
  build_windows_msvc_base:
    name: build_conduit MSVC Base Release
    runs-on: windows-2025
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13
    - name: Setup MPI
      uses: mpi4py/setup-mpi@8ac56ec7ab12f2dffdcf55ffaf50f1920ebcc004 # v1
    - name: Setup Python Env
      run: python -m pip install --upgrade pip numpy mpi4py wheel setuptools
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      with:
        submodules: 'recursive'
    - name: Build TPLs
      run: |
        env build_conduit=false \
            enable_tests=OFF \
            enable_zfp=OFF \
            enable_python=OFF \
            build_pyvenv=false \
            ./scripts/build_conduit/build_conduit.sh
      shell: bash
    - name: Echo Host Config
      run: |
            echo "**** Generated host-config"
            echo conduit-config.cmake
      shell: bash
    - name: Configure Conduit
      run: |
        cmake --version
        echo "**** Configuring Conduit"
        cmake -S src -B build \
              -C conduit-config.cmake \
              -DENABLE_TESTS=ON \
              -DCMAKE_INSTALL_PREFIX=install
      shell: bash
    - name: Build Conduit
      run: |
        echo "**** Building Conduit"
        cmake --build build --config Release -j2
      shell: bash
    - name: Run Conduit Unit Tests
      run: |
        echo "**** Conduit Unit Tests"
        cmake -E env CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --config Release --target RUN_TESTS
      shell: bash
    - name: Install Conduit
      run: |
        echo "**** Installing Conduit"
        cmake --install build --config Release
      shell: bash


