name: Windows

on:
  pull_request:
    branches: [ develop ]

jobs:
  build_windows_msvc:
    name: MSVC Base with Python
    runs-on: windows-latest   
    steps:
    - name: Setup Python Env
      run: python3 -m pip install --upgrade pip numpy
    - uses: actions/checkout@v2
      with: 
        submodules: 'recursive'
    - name: Build & Install
      run: |
        cmake -S src -B build             `
              -DCMAKE_BUILD_TYPE=Release    `
              -DENABLE_PYTHON=ON
        cmake --build build --config Release --parallel 2
