name: Windows

on:
  pull_request:
    branches: [ develop ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_windows_msvc:
    name: MSVC Base with Python
    runs-on: windows-latest   
    steps:
    - name: Setup Python Env
      run: python3 -m pip install --upgrade numpy
    - uses: actions/checkout@v2
    - name: Build & Install
      run: |
        cmake -S . -B build               `
              -DCMAKE_BUILD_TYPE=Debug    `
              -DENABLE_PYTHON=ON          `
              -DPYTHON_EXECUTABLE=python3
        cmake --build build --config Debug --parallel 2
